version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: devproj-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: devproj-backend
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/devopsdb
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    container_name: devproj-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mongo_data:
